# Generated by Django 4.1.5 on 2023-01-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cakes",
            name="description",
            field=models.TextField(max_length=150),
        ),
    ]
