# Generated by Django 4.1.5 on 2023-01-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_cakes_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cakes",
            name="description",
            field=models.TextField(max_length=200),
        ),
    ]
