# Generated by Django 4.1.5 on 2023-01-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_rename_imagen_cakes_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cakes",
            options={"verbose_name": "cake", "verbose_name_plural": "cakes"},
        ),
    ]
