# Generated by Django 4.1.5 on 2023-02-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderline",
            old_name="order_id",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="orderline",
            old_name="product_id",
            new_name="product",
        ),
    ]
